base_url = "https://cosmevalera.github.io"
title = "Home | Cosme"

compile_sass = true

[markdown]
highlight_code = false

build_search_index = false

[extra]
links = [
    { title = "GitHub", url = "https://github.com/CosmeValera", icon = "github" },
    { title = "LinkedIn", url = "https://www.linkedin.com/in/cosmevalera/", icon = "linkedin" }
]

nav = [
    { name = "Projects", path = "/projects/", class = "menu-item" },
    { name = "Blog", path = "/blog/", class = "menu-item" },
]

favicon = "favicon.jpg"